language: python
cache: pip
python:
- '3.6'
install:
- pip install coveralls
- pip install codecov
script: xvfb-run coverage run -m unittest
after_success:
- coveralls
- codecov
deploy:
  provider: pypi
  user: tedlaz
  password:
    secure: zn8rzqtDexyn1owVQtvt6v40c3BtruC5W3fVkXXfl+B4mlALvVWYdagsHc44eh961kJTEuM6WNKpS+esS2rfmsqTyammp0Ao2hduAS1ZpSgxrwAri2OxROz8GP6k0XZk0nf+b87/F4Bzakopjv3N3RxwXilzYzeMvaSPaFJeeW2cl4IdEX8mEwthDn/d0yG/bdC+ujsBHujHMbmTRoZZtrR7OmKO+YvAp+wLR9wiUWA6NNNtw66J75pAfhBxrn2uhmqUrZXffrDSbOn3krBLNtKPHZparCpSN4QPcXSCFxJW8LCaRU1oY6UaD6yh2W0zaGPVgUDFRmuY5iX9hIzFEr1BgfQBRzbtQWrRyZ4zkSDfTjgR/hH9GcEv3sMNjipC+hmOWlYP0RVKDgIO4x6vv3azdjf8ej9N2at7bFOWLHB2yBpJ2sAjJGJQSNkGRi8qG79uFoGqVVYEe3TN249R/3ja+C6LcxygFrGlM7man5ae1BYMA/elFcHiwnsjT0yMqvEFUF2zkNO2AoxobWaq58m1TLgEfmMSnubYDfxd1bxyKY52Rx/I8EFI/UYpRO4BnzazxeUjU/1nTQTJhIkIwo1p5uWTlOLsfEBt9QMCvY21ISpjx7VmO5kjGlJJds3RnStQFkLUBq3ua86w2vWmZRTsXBsakq6Jxok6FNQZ1uQ=
#  on:
#    tags: true
